backend:
  name: github
  repo: Soft-Solutions-Tech/EMC-website
  branch: main
  base_url: https://emc-vert.vercel.app
  auth_endpoint: /api/decap-oauth/auth

site_url: https://emc-vert.vercel.app

media_folder: "my-app/public/uploads"
public_folder: "/uploads"

publish_mode: editorial_workflow

# Enable preview
preview_path: /admin
preview_path_date_field: date

collections:
  - name: site
    label: Site Content
    files:
      - name: hero
        label: Hero
        file: my-app/data/hero.json
        format: json
        editor:
          preview: true
        fields:
          - label: Hero
            name: hero
            widget: object
            fields:
              - { label: Badge, name: badge, widget: string }
              - { label: Subheading, name: subheading, widget: text }
              - { label: Primary CTA, name: ctaPrimary, widget: string }
              - { label: Secondary CTA, name: ctaSecondary, widget: string }

      - name: about
        label: About
        file: my-app/data/about.json
        format: json
        editor:
          preview: true
        fields:
          - label: Founders
            name: founders
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Education, name: education, widget: string }
              - label: Career
                name: career
                widget: list
                field: { label: Item, name: item, widget: string }
              - { label: Image, name: image, widget: string }
          - label: Company Timeline
            name: companyTimeline
            widget: list
            fields:
              - { label: Year, name: year, widget: number }
              - { label: Event, name: event, widget: string }
          - label: Company Overview
            name: companyOverview
            widget: object
            fields:
              - { label: Established, name: established, widget: string }
              - { label: Location, name: location, widget: string }
              - { label: Capital, name: capital, widget: string }
              - { label: Turnover, name: turnover, widget: string }
              - { label: Dubai Branch, name: dubaiBranch, widget: string }
              - { label: Partner Since, name: partnerSince, widget: string }
              - { label: Focus, name: focus, widget: string }
              - { label: Mission, name: mission, widget: string }
          - label: Content
            name: content
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Description, name: description, widget: text }

      - name: info
        label: Info Stats
        file: my-app/data/info.json
        format: json
        editor:
          preview: true
        fields:
          - label: EMC Info
            name: emcInfo
            widget: object
            fields:
              - label: Summary
                name: summary
                widget: text
              - label: Stats
                name: stats
                widget: list
                fields:
                  - { label: Value, name: value, widget: number }
                  - {
                      label: Suffix,
                      name: suffix,
                      widget: string,
                      required: false,
                    }
                  - { label: Label, name: label, widget: string }
                  - { label: Description, name: description, widget: string }
              - { label: Header Title, name: headerTitle, widget: string }

      - name: services
        label: Services
        file: my-app/data/ourservices.json
        format: json
        editor:
          preview: true
        fields:
          - label: Services
            name: services
            widget: list
            fields:
              - { label: ID, name: id, widget: string }
              - {
                  label: Type,
                  name: type,
                  widget: select,
                  options: [EPC, CONSULTING, AFTERSALES],
                }
              - { label: Title, name: title, widget: string }
              - { label: Description, name: description, widget: text }
              - label: Features
                name: features
                widget: list
                field: { label: Feature, name: feature, widget: string }
          - label: Section
            name: servicesSection
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Subtitle, name: subtitle, widget: text }

      - name: activities
        label: Activities
        file: my-app/data/activities.json
        format: json
        editor:
          preview: true
        fields:
          - label: Activities
            name: activities
            widget: list
            fields:
              - { label: ID, name: id, widget: string }
              - { label: Title, name: title, widget: string }
              - { label: Description, name: description, widget: text }
              - { label: Icon, name: icon, widget: string }

      - name: coreValues
        label: Core Values
        file: my-app/data/coreValues.json
        format: json
        editor:
          preview: true
        fields:
          - label: Company Info
            name: companyInfo
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Description, name: description, widget: text }
          - label: Core Values
            name: coreValues
            widget: list
            fields:
              - { label: Text, name: text, widget: string }
              - { label: Icon, name: icon, widget: string }
              - { label: Short Description, name: desc, widget: string }
              - { label: Full Description, name: fullDesc, widget: text }
              - { label: Color, name: color, widget: string }
              - { label: Background Color, name: bgColor, widget: string }

      - name: partners
        label: Partners
        file: my-app/data/partners.json
        format: json
        editor:
          preview: true
        fields:
          - label: Partners
            name: partners
            widget: list
            fields:
              - { label: ID, name: id, widget: string }
              - { label: Name, name: name, widget: string }
              - { label: Logo, name: logo, widget: string }
              - { label: Brief, name: brief, widget: string }
              - {
                  label: Website,
                  name: website,
                  widget: string,
                  required: false,
                }
              - name: subCompanies
                label: Sub Companies
                widget: list
                field: { label: Name, name: name, widget: string }
          - label: Section
            name: partnersSection
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Subtitle, name: subtitle, widget: text }
              - { label: Label, name: label, widget: string }

      - name: clients
        label: Clients
        file: my-app/data/clients.json
        format: json
        editor:
          preview: true
        fields:
          - label: Clients
            name: clients
            widget: list
            fields:
              - { label: ID, name: id, widget: string }
              - { label: Name, name: name, widget: string }
              - { label: Logo, name: logo, widget: string }
              - { label: Brief, name: brief, widget: string }
              - {
                  label: Website,
                  name: website,
                  widget: string,
                  required: false,
                }
              - name: subCompanies
                label: Sub Companies
                widget: list
                field: { label: Name, name: name, widget: string }
          - label: Section
            name: clientsSection
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Subtitle, name: subtitle, widget: text }
              - { label: Label, name: label, widget: string }

      - name: projects
        label: Projects
        file: my-app/data/projects.json
        format: json
        editor:
          preview: true
        fields:
          - label: Section Title
            name: portfolioTitle
            widget: string
          - label: Section Headings
            name: sectionHeadings
            widget: list
            fields:
              - { label: Label, name: label, widget: string }
              - { label: Index, name: idx, widget: number }
              - label: Description
                name: desc
                widget: list
                field: { label: Line, name: line, widget: string }
          - label: Projects
            name: projects
            widget: list
            fields:
              - { label: ID, name: id, widget: string }
              - { label: Name, name: name, widget: string }
              - {
                  label: Type,
                  name: type,
                  widget: select,
                  options: [EPC, CONSULTING, AFTERSALES],
                }
              - { label: Description, name: description, widget: text }
              - {
                  label: Start Date,
                  name: startDate,
                  widget: string,
                  required: false,
                }
              - {
                  label: End Date,
                  name: endDate,
                  widget: string,
                  required: false,
                }
              - { label: Status, name: status, widget: string }
              - { label: Client, name: client, widget: string, required: false }
              - name: partners
                label: Partners
                widget: list
                field: { label: Partner, name: partner, widget: string }
              - { label: Value, name: value, widget: string, required: false }
              - {
                  label: Location,
                  name: location,
                  widget: string,
                  required: false,
                }
              - name: images
                label: Images
                widget: list
                field: { label: Image, name: image, widget: string }
              - {
                  label: Consulting CTA,
                  name: consultingCta,
                  widget: string,
                  required: false,
                }

  # Separate collection for adding new projects
  - name: newProjects
    label: Add New Project
    folder: my-app/data/projects
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: ID,
          name: id,
          widget: string,
          hint: "Unique project ID (e.g., p64)",
        }
      - { label: Name, name: name, widget: string }
      - {
          label: Type,
          name: type,
          widget: select,
          options: [EPC, CONSULTING, AFTERSALES],
        }
      - { label: Description, name: description, widget: text }
      - {
          label: Start Date,
          name: startDate,
          widget: string,
          required: false,
          hint: "YYYY-MM-DD format",
        }
      - {
          label: End Date,
          name: endDate,
          widget: string,
          required: false,
          hint: "YYYY-MM-DD format",
        }
      - {
          label: Status,
          name: status,
          widget: select,
          options: [Active, Finished, Planning],
        }
      - { label: Client, name: client, widget: string, required: false }
      - name: partners
        label: Partners
        widget: list
        field: { label: Partner, name: partner, widget: string }
      - { label: Value, name: value, widget: string, required: false }
      - { label: Location, name: location, widget: string, required: false }
      - name: images
        label: Images
        widget: list
        field:
          {
            label: Image Path,
            name: image,
            widget: string,
            hint: "e.g., /uploads/projects/project-name.jpg",
          }
      - {
          label: Consulting CTA,
          name: consultingCta,
          widget: string,
          required: false,
        }
